services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: php artisan octane:frankenphp --max-requests=1
    ports:
      - "80:8000"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./src:/app